export const JWT_SECRET = 'DUMMY JWT SECRET (should come from process.env)';
export const ENV_API_PREFIX = 'CB_API_PREFIX';
export const ENV_MASTER_KEY = 'CB_MASTER_KEY';
export const ENV_HOST = 'CB_HOST';
export const ENV_PORT = 'CB_PORT';
export const ENV_CORS = 'CB_CORS';
export const ENV_CRAWLER_SEEDS = 'CRAWLER_SEEDS';
export const ENV_CRAWLER_CONCURRENCY = 'CRAWLER_CONCURRENCY';
export const ENV_CRAWLER_MAX_REQUESTS_PER_CRAWL =
  'CRAWLER_MAX_REQUESTS_PER_CRAWL';
export const ENV_CRAWLER_TIMEOUT_MS = 'CRAWLER_TIMEOUT_MS';
export const ENV_CRAWLER_PROXY_URL = 'CRAWLER_PROXY_URL';
export const ENV_CRAWLER_DATA_DIR = 'CRAWLER_DATA_DIR';
export const ENV_CRAWLER_DATASET_NAME = 'CRAWLER_DATASET_NAME';
export const ENV_CRAWLER_QUEUE_NAME = 'CRAWLER_QUEUE_NAME';
export const ENV_CRAWLER_KV_STORE_NAME = 'CRAWLER_KV_STORE_NAME';
export const ENV_CRAWLER_USE_BROWSER = 'CRAWLER_USE_BROWSER';
export const ENV_CRAWLER_DEFAULT_NAME = 'CRAWLER_DEFAULT_NAME';
export const ENV_CRAWLER_REDIS_URL = 'CRAWLER_REDIS_URL';
export const ENV_CRAWLER_REDIS_QUEUE_KEY = 'CRAWLER_REDIS_QUEUE_KEY';
export const ENV_CRAWLER_MIN_WORKERS = 'CRAWLER_MIN_WORKERS';
export const ENV_CRAWLER_MAX_WORKERS = 'CRAWLER_MAX_WORKERS';
export const ENV_CRAWLER_RAM_PER_WORKER_MB = 'CRAWLER_RAM_PER_WORKER_MB';
export const ENV_CRAWLER_RAM_UTILIZATION = 'CRAWLER_RAM_UTILIZATION';
export const ENV_CRAWLER_AUTOSCALE_INTERVAL_MS =
  'CRAWLER_AUTOSCALE_INTERVAL_MS';
export const ENV_CRAWLER_QUEUE_POLL_INTERVAL_MS =
  'CRAWLER_QUEUE_POLL_INTERVAL_MS';
export const ENV_CRAWLER_MAX_PAGES_PER_SITE = 'CRAWLER_MAX_PAGES_PER_SITE';
